ip_list:
  description: ip list
  resource_name: projects/secops-test-01/locations/us/instances/bd156754-2715-465a-ba27-59e6602952fd/referenceLists/ip_list
  revision_create_time: '2024-10-31T17:13:32.528287Z'
  rule_associations_count: null
  rules: null
  syntax_type: REFERENCE_LIST_SYNTAX_TYPE_CIDR
